version: "3"
services:
  frontend:
    build:
      context: ../bus-tracker-frontend
      dockerfile: build/Dockerfile
    ports:
    - "3000:80"

  tracker:
    build:
      context: ../bus-tracker-backend
      dockerfile: build/Dockerfile
    ports:
    - "8000:8000"
    environment:
      BUS_TRACKER_TIMEOUT: "0.3"
    networks:
      tracker-network:

  emulator:
    build:
      context: ../bus-tracker-backend
      dockerfile: build/Dockerfile
    environment:
      BUS_EMULATOR_SERVER: "ws://tracker:8080"
#      BUS_EMULATOR_ROUTES: 1  # default == max == 595
      BUS_EMULATOR_BUSES_PER_ROUTE: 5
      BUS_EMULATOR_TIMEOUT: "0.3"
    command: ["emulator"]
    depends_on:
      - tracker
    networks:
      tracker-network:


networks:
  tracker-network:
