name: code-quality
on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          cd bus-tracker-backend
          python -m pip install --upgrade pip
          pip install poetry
          make install-dev
      - name: Lint with flake8
        run: |
          cd bus-tracker-backend
          make lint
      - name: Check typing with mypy
        run: |
          cd bus-tracker-backend
          make mypy

  tests:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        cd bus-tracker-backend
        python -m pip install --upgrade pip
        pip install poetry
        make install-dev
    - name: Test with pytest
      run: |
        cd bus-tracker-backend
        make tests
